azure: &azure
  service: AzureStorage
  storage_account_name: <%= Rails.application.credentials.dig(:azure, :account_name) %>
  storage_access_key: <%= Rails.application.credentials.dig(:azure, :account_key) %>

primary:
  <<: *azure
  container: primary

derivatives:
  <<: *azure
  container: derivatives
  public: true
