azure: &azure
  service: AzureStorage
  storage_account_name: <%= ENV['AZURE_STORAGE_ACCOUNT_NAME'] %>
  storage_access_key: <%= ENV['AZURE_STORAGE_ACCOUNT_KEY'] %>

primary:
  <<: *azure
  container: primary

derivatives:
  <<: *azure
  container: derivatives
  public: true
