default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: 'curator,public'

development:
  <<: *default
  database: curator_api_development
  username: <%= ENV.fetch('CURATOR_API_PG_USER') { postgres } %>
  password: <%= ENV.fetch('CURATOR_API_PG_PASS') { postgres } %>
  host: <%= ENV.fetch('CURATOR_API_PG_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('CURATOR_API_PG_PORT') { 5432 } %>

test:
  <<: *default
  database: curator_api_test
  username: <%= ENV.fetch('CURATOR_API_PG_USER') { postgres } %>
  password: <%= ENV.fetch('CURATOR_API_PG_PASS') { postgres } %>
  host: <%= ENV.fetch('CURATOR_API_PG_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('CURATOR_API_PG_PORT') { 5432 } %>

staging:
  <<: *default
  database: curator_api_staging
  username: <%= ENV.fetch('CURATOR_API_PG_USER') { Rails.application.secrets.dig(:postgres, :user) } %>
  password: <%= ENV.fetch('CURATOR_API_PG_PASS') { Rails.application.secrets.dig(:postgres, :password) } %>
  host: <%= ENV.fetch('CURATOR_API_PG_HOST') { Rails.application.secrets.dig(:postgres, :host) } %>
  port: <%= ENV.fetch('CURATOR_API_PG_PORT') {  Rails.application.secrets.dig(:postgres, :port) } %>


production:
  <<: *default
  database: curator_api_production
  username: <%= ENV.fetch('CURATOR_API_PG_USER') { Rails.application.secrets.dig(:postgres, :user) } %>
  password: <%= ENV.fetch('CURATOR_API_PG_PASS') { Rails.application.secrets.dig(:postgres, :password) } %>
  host: <%= ENV.fetch('CURATOR_API_PG_HOST') { Rails.application.secrets.dig(:postgres, :host) } %>
  port: <%= ENV.fetch('CURATOR_API_PG_PORT') {  Rails.application.secrets.dig(:postgres, :port) } %>
