:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - curator_app_indexing
  - curator_app_arks
  - curator_app_filestream_derivatives
  - curator_app_iiif
  - curator_app_default
